name:                copyRepoIssues
version:             0.1.0.0
github:              "angelpopov/copyRepoIssues"
license:             BSD3
author:              "Angel Popov"
maintainer:          "angelpopov@yahoo.com"
copyright:           "na"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            hello

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/angelpopov/copyRepoIssues#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - split
    - aeson
    - lens
    - lens-aeson
    - text
    - scientific
    - vector
    - http-conduit
    - case-insensitive
    - bytestring
    - mtl

executables:
  copyRepoIssues-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copyRepoIssues
    - optparse-applicative
    - mtl

tests:
  copyRepoIssues-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - copyRepoIssues
